config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  ActiveAdmin.routes(self)
  devise_for :users
  root 'organizations#index'
  resources :categories
  resources :organizations do
    resources :orgcomments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/orgcomment.rb
class Orgcomment < ApplicationRecord
  belongs_to :user
  belongs_to :organization
end

app/controllers/orgcomments_controller.rb
class OrgcommentsController < InheritedResources::Base
  before_action :set_post
  def create
    @orgcomment = @organization.orgcomments.build(orgcomment_params)
    @orgcomment.user_id = current_user.id
    if @orgcomment.save
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    else
      flash[:alert] = "Check the comment form, something went wrong."
      render root_path
    end
  end
  private

    def orgcomment_params
      params.require(:orgcomment).permit(:title,:user_id, :organization_id)
    end
  def set_post
    @organization = Organization.find(params[:organization_id])
  end
end

app/helpers/orgcomments_helper.rb
module OrgcommentsHelper
end

app/views/orgcomments/_form.html.erb
<%= form_for(orgcomment) do |f| %>
  <% if orgcomment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(orgcomment.errors.count, "error") %> prohibited this orgcomment from being saved:</h2>

      <ul>
      <% orgcomment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_area :title %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orgcomments/_orgcomment.html.erb
<div class="comment-content">
  <%= orgcomment.title %>

</div>

app/views/orgcomments/create.js.erb
$('#comments_<%= @organization.id %>').append("<%=j render 'orgcomments/orgcomment', organization: @organization, orgcomment: @orgcomment %>");
$('#comment_content_<%= @organization.id %>').val('')

app/views/orgcomments/edit.html.erb
<h1>Editing Orgcomment</h1>

<%= render 'form', orgcomment: @orgcomment %>

<%= link_to 'Show', @orgcomment %> |
<%= link_to 'Back', orgcomments_path %>

app/views/orgcomments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orgcomments</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orgcomments.each do |orgcomment| %>
      <tr>
        <td><%= orgcomment.title %></td>
        <td><%= link_to 'Show', orgcomment %></td>
        <td><%= link_to 'Edit', edit_orgcomment_path(orgcomment) %></td>
        <td><%= link_to 'Destroy', orgcomment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Orgcomment', new_orgcomment_path %>

app/views/orgcomments/new.html.erb
<h1>New Orgcomment</h1>

<%= render 'form', orgcomment: @orgcomment %>

<%= link_to 'Back', orgcomments_path %>

app/views/orgcomments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @orgcomment.title %>
</p>

<%= link_to 'Edit', edit_orgcomment_path(@orgcomment) %> |
<%= link_to 'Back', orgcomments_path %>