config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  ActiveAdmin.routes(self)
  devise_for :users
  root 'organizations#index'
  resources :categories
  resources :organizations do
    resources :orgcomments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/organization.rb
class Organization < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :orgcomments, dependent: :destroy
  ratyrate_rateable "speed", "engine", "price","overall_average"

  has_attached_file :image,
                    styles: { medium: '300x300>', thumb: '100x100>'},
                    default_url: '/images/:style/missing.png'
  validates_attachment_content_type :image,
                                    content_type: ['image/jpeg', 'image/gif', 'image/png']

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.paginate(:page => params[:page], :per_page => 20).order('id DESC').where(active: true)
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end



  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:title, :description, :active,:category_id,:user_id,:image,:active,:orgcomment_id)
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= form_for(organization) do |f| %>
  <% if organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
    <div class="field">
      <%= f.label :category %>
      <%= f.collection_select :category_id, Category.all,:id, :title%>
    </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">

    <%= f.hidden_field :active %>
  </div>
  <div>
    <%= f.file_field :image %>
  </div>
    <%= f.hidden_field :user_id, value: current_user.id %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing Organization</h1>

<%= render 'form', organization: @organization %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<p id="notice"><%= notice %></p>





<div class="container">
  <div class="new_organization col-md-12">
    <%= will_paginate @organizations %>

    <% @organizations.each do |organization| %>
        <div class="col-md-4">
          <h4><%= link_to organization.title, organization %></h4>
          <ul>
            <li><%= 'Описание' %>: <%= organization.description %></li>
            <li><%= 'Категория' %>: <%= organization.category.title %></li>
            <li><%= image_tag organization.image.url(:thumb) %></li>
            <li>Обслуживание  : <%= rating_for organization, 'speed', star: 5 %></li>
            <li>Качество : <%= rating_for organization, 'engine', star: 5 %></li>
            <li>Цена  : <%= rating_for organization, 'price', star: 5 %></li>
          </ul>
        </div>
    <% end %>

  </div>
  <br>
  <br>
  <% if user_signed_in? %>
      <%= link_to 'Create New Organization', new_organization_path %>
  <% end %>

</div>

app/views/organizations/new.html.erb
<h1>New Organization</h1>

<%= render 'form', organization: @organization %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @organization.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @organization.description %>
</p>
<p>Comments: <%= render @organization.orgcomments %></p
<li><%= image_tag @organization.image.url(:thumb) %></li>
<li><%= rating_for @organization, 'speed', disable_after_rate: true %></li>
<li><%= rating_for @organization, 'engine', disable_after_rate: true %></li>
<li><%= rating_for @organization, 'price', disable_after_rate: true %></li>

<div class="comment-form col-sm-11">
  <%= form_for([@organization, @organization.orgcomments.build], remote: true) do |f| %>

      <%= f.text_field :title, placeholder: 'Add a comment...', class: "comment_content", id: "comment_content_#{@organization.id}",remote: true%>
  <% end %>
</div>
<% if user_signed_in? %>
<% if current_user.id == @organization.user_id %>
<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>
<% end %>
<% end %>